name: 04 - Using Actions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Golang
        uses: actions/setup-go

      - name: Install Dependencies
        run: go mod download
