name: 05 - 1 - Filters Activity Types

on:
  workflow_dispatch:
#  pull_request:
#    types:
#      - opened
#      - synchronize
#      - closed
#    branches:
#      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for open|synchronized PR
        run: echo 'Running whenever a PR is opened or synchronized AND base branch is main'